export const AUTHENTICATE = "AUTHENTICATE";

export const FETCH_PROFILE = "FETCH_PROFILE";
export const CREATE_INTRO = "CREATE_INTRO";
export const UPDATE_INTRO = "UPDATE_INTRO";
export const CREATE_EDUCATION = "CREATE_EDUCATION";
export const UPDATE_EDUCATION = "UPDATE_EDUCATION";
export const DELETE_EDUCATION = "DELETE_EDUCATION";
export const CREATE_EXPERIENCE = "CREATE_EXPERIENCE";
export const UPDATE_EXPERIENCE = "UPDATE_EXPERIENCE";
export const DELETE_EXPERIENCE = "DELETE_EXPERIENCE";

export const MODAL_OPEN = "MODAL_OPEN";
export const MODAL_CLOSE = "MODAL_CLOSE";
